services:
  php:
    image: php:8.0-fpm
    volumes:
      - ./:/var/www/html  # Mount your PHP code to the container
    networks:
      - php-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Nginx configuration
      - ./:/var/www/html  # Share the same PHP code
    ports:
      - "80:80"  # Expose port 80 on the host to access the site
    depends_on:
      - php
    networks:
      - php-network

networks:
  php-network:
    driver: bridge
